# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Laternray
email: bela@example.com
description: >- # this means to ignore newlines until "baseurl:"
  whelcome to my brand new website: 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll_site" # the subpath of your site, e.g. /blog
url: "https://b-abdou-dev.github.io/jekyll_site/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bela
github_username:  bela


# bellow is section of new fields that are not defaulted by minima theme
# author field used in minima theme, but not defaulted.     ..added
author: A.Bela

# copyright field used in minima theme, but not defaulted.   ..added
copyright: "Techscan"

# for adding social media account in the footer use the following variables --copied from social.html     .. added
youtube_username:
github_username: 
#linkedin_username: 
#twitter_username:
#facebook_username:

# adding logo
title-logo: /images/title-logo.png




# Build settings

# remove minima theme       .. added
# theme: minima             .. commented
plugins:  
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
